services:
  server:
    build:
      context: .
      args:
        environment: ${NODE_ENV}
    env_file:
      - .env
    develop:
      watch:
        - action: sync
          path: ./src
          target: /usr/pcso-lotto-api/src
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json
    # ports:
    #   - "3000:3000"
    depends_on:
      - redis
  redis:
    image: "redis:latest"
    # ports:
    #   - "6379:6379"
  nginx:
    image: nginx:1.28.0
    depends_on:
      - server
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:80
    restart: on-failure