services:
  server:
    build:
      context: .
      args:
        environment: ${NODE_ENV}
    env_file:
      - .env
    develop:
      watch:
        - action: sync
          path: ./src
          target: /usr/pcso-lotto-api/src
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json
    ports:
      - "3000:3000"
    depends_on:
      - redis
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"